apiVersion: v1
kind: LimitRange
metadata:
  name: mem-cpu-example
spec:
  limits:
  - default:
        cpu : 500m
        memory : 256Mib
    defaultRequest:
        cpu: 100m
        memory : 64Mib
    max: 
        cpu : 1000m
        memory: 512Mib
    min: 
        cpu : 1000m
        memory: 512Mib